const dishes=[
{id:"pad",name:"Pad Thaï",price:11,emoji:"🍜",photo:"photo-pad",desc:"Nouilles de riz sautées, crevettes, œuf, tofu, pousses de soja et cacahuètes.",spicy:true},
{id:"jour",name:"Plat thaï du jour",price:9,emoji:"🍛",photo:"photo-krapow",desc:"Exemple du jour : Khao Pad Krapow, poulet au basilic thaï, ail et piment, servi avec riz jasmin.",spicy:true},
{id:"kids",name:"Menu enfant",price:6,emoji:"🍗",photo:"photo-kids",desc:"2 pilons de poulet frit + frites, ou 2 nems + riz.",spicy:false},
{id:"nems",name:"Nems",price:1,emoji:"🥢",photo:"photo-nems",desc:"Nems thaïlandais croustillants, à l’unité.",spicy:false},
{id:"samoussa",name:"Samoussa",price:1.5,emoji:"🥟",photo:null,desc:"Samoussa croustillant, à l’unité.",spicy:false},
{id:"spring",name:"Spring roll",price:3,emoji:"🌯",photo:null,desc:"Rouleau frais préparé avec les ingrédients du jour.",spicy:false},
{id:"mango",name:"Sticky rice mangue",price:4,emoji:"🥭",photo:"photo-mango",desc:"Riz gluant au lait de coco et mangue fraîche, selon saison.",spicy:false},
{id:"drink",name:"Boisson",price:2,emoji:"🥤",photo:null,desc:"Eau ou soda.",spicy:false}
];
const SERVICE_WINDOWS=[{label:"Service midi",start:"11:30",end:"14:00"},{label:"Service soir",start:"18:30",end:"21:00"}];
const PREP={pad:{base:8,extra:2},jour:{base:7,extra:2},kids:{base:5,extra:1.5},nems:{base:2,extra:.5},samoussa:{base:2,extra:.5},spring:{base:1.5,extra:.3},mango:{base:2,extra:.5},drink:{base:.5,extra:.2}};
let cart=[],orders=[],selectedSpice={};
const euro=n=>n.toLocaleString("fr-FR",{style:"currency",currency:"EUR"}),$=s=>document.querySelector(s);
const loadOrders=()=>{try{return JSON.parse(localStorage.getItem("tammyOrders")||"[]")}catch{return[]}};
const saveOrders=()=>localStorage.setItem("tammyOrders",JSON.stringify(orders));
function renderMenu(){const el=$("#menu-grid");if(!el)return;el.innerHTML=dishes.map(d=>{const qty=cart.filter(i=>i.id===d.id).reduce((s,i)=>s+i.qty,0),spice=selectedSpice[d.id]||0;return `<article class="card"><div class="pic ${d.photo||"no-photo"}">${d.photo?"":`<span>${d.emoji}</span>`}</div><div class="cardbody"><div class="dish-title"><h3>${d.name}</h3><b>${euro(d.price)}</b></div><p>${d.desc}</p>${d.spicy?`<div class="spice-row"><span class="control-label">Piment</span><button class="mini" onclick="changeSpice('${d.id}',-1)">−</button><span class="peppers">${[0,1,2].map(n=>`<span class="${n<spice?'active':''}">🌶️</span>`).join("")}</span><button class="mini" onclick="changeSpice('${d.id}',1)">+</button><span class="spice-level">${spice}/3</span></div>`:""}<div class="qty-row"><span class="control-label">Quantité</span><button class="qty" onclick="removeOne('${d.id}')">−</button><strong>${qty}</strong><button class="qty" onclick="add('${d.id}')">+</button></div></div></article>`}).join("")}
function changeSpice(id,d){selectedSpice[id]=Math.max(0,Math.min(3,(selectedSpice[id]||0)+d));renderMenu()}
function add(id){const spice=selectedSpice[id]||0,x=cart.find(i=>i.id===id&&i.spice===spice);x?x.qty++:cart.push({id,qty:1,spice});renderAll();toast("Plat ajouté au panier")}
function removeOne(id){const x=cart.filter(i=>i.id===id).sort((a,b)=>b.spice-a.spice)[0];if(!x)return;x.qty--;if(x.qty<1)cart=cart.filter(i=>i!==x);renderAll()}
function cartTotal(){return cart.reduce((s,i)=>s+dishes.find(d=>d.id===i.id).price*i.qty,0)}
function renderCart(){const n=cart.reduce((s,i)=>s+i.qty,0);const total=$("#top-total"),count=$("#top-count"),endTotal=$("#cart-end-total"),endCount=$("#cart-end-count"),button=$("#checkout-button");if(total)total.textContent=euro(cartTotal());if(count)count.textContent=`${n} article${n>1?"s":""}`;if(endTotal)endTotal.textContent=euro(cartTotal());if(endCount)endCount.textContent=`${n} article${n>1?"s":""}`;if(button){button.disabled=!n;button.style.opacity=n?"1":".5"}}
function renderAll(){renderMenu();renderCart()}
function serviceNow(){const m=new Date().getHours()*60+new Date().getMinutes();return SERVICE_WINDOWS.find(w=>{const[a,b]=w.start.split(":").map(Number),[c,d]=w.end.split(":").map(Number);return m>=a*60+b&&m<c*60+d})}
function nextService(){const m=new Date().getHours()*60+new Date().getMinutes();return SERVICE_WINDOWS.find(w=>{const[a,b]=w.start.split(":").map(Number);return m<a*60+b})||SERVICE_WINDOWS[0]}
function slots(w){const out=[];let[h,m]=w.start.split(":").map(Number),[eh,em]=w.end.split(":").map(Number);while(h*60+m<=eh*60+em-15){out.push(`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`);m+=15;if(m>=60){h++;m-=60}}return out}
function work(order,previous=[]){const counts={};previous.filter(o=>o.status!=="ready").forEach(o=>o.items.forEach(i=>counts[i.id]=(counts[i.id]||0)+i.qty));let t=0;order.items.forEach(i=>{const p=PREP[i.id]||{base:3,extra:1};t+=(counts[i.id]?p.base*.7:p.base)+Math.max(0,i.qty-1)*p.extra});return Math.max(1,Math.ceil(t))}
function projection(){let t=0;const active=orders.filter(o=>o.status!=="ready").sort((a,b)=>a.createdAt-b.createdAt);return active.map((o,i)=>{const w=work(o,active.slice(0,i));t+=w;return{order:o,wait:Math.ceil(t),work:w}})}
function estimate(){return Math.max(1,work({items:cart},orders.filter(o=>o.status!=="ready"))+projection().reduce((s,x)=>s+x.work,0))}
function openCheckout(){if(!cart.length)return toast("Votre panier est vide");const current=serviceNow(),w=current||nextService();$("#modal-total").textContent=euro(cartTotal());$("#modal-wait").textContent=`~${estimate()} min`;$("#service-info").textContent=current?`Service en cours : ${w.label}, jusqu'à ${w.end}.`:`Prochain service : ${w.label}, ${w.start}–${w.end}.`;$("#slot").innerHTML=slots(w).map(s=>`<option>${s}</option>`).join("");$("#checkout-modal").classList.add("show")}
function closeCheckout(){$("#checkout-modal").classList.remove("show")}
function placeOrder(){if(!cart.length)return toast("Votre panier est vide");const id="#"+String(Date.now()).slice(-4),order={id,status:"waiting",slot:$("#slot").value,estimatedMinutes:estimate(),createdAt:Date.now(),total:cartTotal(),items:cart.map(i=>({...i,name:dishes.find(d=>d.id===i.id).name}))};orders=loadOrders();orders.push(order);saveOrders();localStorage.setItem("tammyLastOrder",order.id);cart=[];closeCheckout();renderAll();toast(`Commande ${id} confirmée`);setTimeout(()=>{window.location.href="suivi.html"},350)}
function renderTracking(order){const status=$("#client-status"),box=$("#client-tracking");if(!status||!box)return;if(!order){status.textContent="Aucune commande";return}const p=projection().find(x=>x.order.id===order.id),idx=p?projection().findIndex(x=>x.order.id===order.id)+1:null,text={waiting:"En attente",cooking:"Tammy prépare votre commande",ready:"Votre commande est prête"}[order.status],cur=["waiting","cooking","ready"].indexOf(order.status);status.textContent=text;box.innerHTML=`<div class="tracking-top"><div><span>Commande ${order.id}</span><h3>${text}</h3></div><strong>Retrait ${order.slot}</strong></div><div class="progress">${["En attente","Préparation","Prête"].map((s,i)=>`<div class="${i<=cur?'done':''}"><span>${i<=cur?'✓':i+1}</span><small>${s}</small></div>`).join("")}</div><div class="tracking-message">${order.status==="waiting"?`⏱️ Position dans la file : <b>${idx||"—"}</b> · temps estimé <b>~${p?p.wait:order.estimatedMinutes} min</b>.`:order.status==="cooking"?`🔥 <b>Votre commande est en cours de préparation.</b>`:`🟢 <b>Votre commande est prête.</b> Vous pouvez venir la récupérer.`}</div>`}
function sync(){const fresh=loadOrders();if(JSON.stringify(fresh)!==JSON.stringify(orders)){orders=fresh;const last=orders[orders.length-1];if(last)renderTracking(last)}}
function toast(t){const x=$("#toast");if(!x)return;x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}
orders=loadOrders();renderAll();const lastId=localStorage.getItem("tammyLastOrder");if(lastId){const last=orders.find(o=>o.id===lastId);if(last)renderTracking(last)}setInterval(sync,1000);